-- 1. Create the Users Table
CREATE TABLE Users (
    UserId VARCHAR(255) NOT NULL,
    Password VARCHAR(255) NOT NULL,
    PRIMARY KEY (UserId)
);

-- 2. Create the Quests Table
CREATE TABLE Quests (
    -- 'GENERATED BY DEFAULT AS IDENTITY' makes this auto-increment (1, 2, 3...)
    QuestID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Prompt TEXT,
    DateCreated BIGINT,
    HostID VARCHAR(255),
    FOREIGN KEY (HostID) REFERENCES Users(UserId)
);

-- 3. Create the Participants Table
CREATE TABLE Participants (
    QuestID INT NOT NULL,
    UserID VARCHAR(255) NOT NULL,
    Score INT,
    TimeTaken BIGINT,
    
    -- FIXED: Changed BLOB to BYTEA for Postgres
    Photo BYTEA, 
    
    -- Composite Primary Key
    PRIMARY KEY (QuestID, UserID),
    
    -- Foreign Keys
    FOREIGN KEY (QuestID) REFERENCES Quests(QuestID),
    FOREIGN KEY (UserID) REFERENCES Users(UserId)
);