PROMPTS = [
    "a red car",
    "a fluffy cat",
    "a snowy mountain",
    "Bowser",
    "a red object",
    "a dog",
    "a fire hydrant",
    "a street sign",
    "a shoe",
    "a chair",
    "a car",
    "a bicycle",
    "a book",
    "a pair of glasses",
    "a coffee cup",
    "a metal can",
    "a laptop",
    "a tree",
    "a set of keys",
    "an outlet",
    "a toilet",
    "a hand",
    "a person",
]