# DBHelper.pyi
from typing import Any, Dict, List, Optional, Union
from supabase import Client

class DBHelper:
    client: Client

    def __init__(self, url: str, key: str) -> None: ...

    def insert_user(self, user_data: Dict[str, Any]) -> Dict[str, Any]: ...

    def get_user(self, user_id: str) -> Optional[Dict[str, Any]]: ...

    def update_participants(self, quest_id: str, participant_updates: Dict[str, Any]) -> List[Dict[str, Any]]: ...

    def insert_quest(self, quest_data: Dict[str, Any]) -> Dict[str, Any]: ...

    def insert_participants(self, participants_data: List[Dict[str, Any]]) -> List[Dict[str, Any]]: ...

    def get_quest(self, quest_id: str) -> Optional[Dict[str, Any]]: ...

    def get_quest_details(self, quest_id: str) -> Dict[str, Any]: ...